parameters:
    Evenement_directory: '%kernel.project_dir%/public/uploads'  
    images_directory: '%kernel.project_dir%/public/uploads/images'
    victor_prdh_recaptcha.google_secret_key: 6Ldn5IwpAAAAALl9IKVUtMlYIxJdwppFJj3Y__q8

services:
    # Default configuration for services in this file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\Services\QrcodeService:
        autowire: true

    VictorPrdh\RecaptchaBundle\Form\ReCaptchaType:
        arguments:
            $parameterBag: '@parameter_bag'

    # Makes classes in src/ available to be used as services
    # This creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Add more service definitions when explicit configuration is needed
    # Please note that last definitions always *replace* previous ones
